from  GUI_classes.class_top_window import Top_Window
from  PyQt4 import QtGui
import sys
import os
import time
import socket

"""
This Function calls the Main window 
"""

def create_log_file():
    """
    Create the log log file in the current directory

    :return: log_path
    """
    log_dir = os.path.join(os.getcwd(),'logs')
    try:
        os.stat(log_dir)
    except:
        os.mkdir(log_dir)

    log_name = time.strftime("%Y%m%d-%H%M%S") + '.log'
    log_path = os.path.join(log_dir,log_name)
    file_handler = open(log_path,'wb')
    file_handler.write('Autogenerated log file created on : ' + time.strftime('%a, %d %b %Y %H:%M:%S') + '\n')
    ip = socket.gethostbyname(socket.gethostname())
    file_handler.write("System IP addrees : " + ip + '\n')
    file_handler.write('-'*80 + '\n')
    file_handler.close()
    return log_path

def call_main_window():
    """
    Create the application main window and pass on the log file path

    :return: None
    """
    app = QtGui.QApplication(sys.argv)
    log_path = create_log_file()
    GUI = Top_Window(log_file_path=log_path)
    sys.exit(app.exec_())

if __name__ == '__main__':
    call_main_window()